name: Main Workflow
run-name: Execute Main Workflow
on:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Dispaly Message in system console
        run: echo "NGINX will be installed here"
  install-nginx:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Install nginx
        run: | 
          sudo apt update
          sudo apt install nginx -y
      - name: Start nginx service
        run: sudo systemctl --now enable nginx

      - name: Add addional line to index.html
        run: sudo sed -i 's|</body>|<p>Hello from GitHub Actions</p></body>|' /var/www/html/index.html

      - name: Verify nginx installation
        run: |
          curl -I localhost | grep "200 OK"
          echo $?  
          ( $? -eq 0 ) && echo "Nginx is installed and running successfully" || ( echo "Nginx installation or verification failed" && exit 1 )